node {
    
    stage 'checkout'
    checkout scm
    def project_path = "spring-boot-samples/spring-boot-sample-atmosphere"

    
    stage 'sonar-scan'
    def scannerHome = tool 'sonar-scanner'
    sh "${scannerHome}/bin/sonar-scanner"
    
     dir(project_path){
     withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]){
     stage 'compiling, packaging'    
     sh 'mvn clean package'
     
     stage 'test-archival/HTML-verify'
     publishHTML(target: [allowMissing: true,
     alwaysLinkToLastBuild: false, 
     keepAll: true, 
     reportDir: 'target/site/jacoco',
     reportFiles: 'index.html', reportName: 'HTML Report'])
     
     step([$class: 'JUnitResultArchiver',
     testResults: 'target/surefire-reports/TEST-*.xml'])


stage 'Upload-artifact-nexus'
     
     withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'b9bc9cc5-871e-4738-88f3-9c3e5525a096',
                    usernameVariable: 'Username', passwordVariable: 'Password']]) {
      sh "curl -XDELETE  -u $Username:$Password http://35.163.156.3:8081/nexus/content/repositories/releases/org/venice/piazza/piazza-ingest/1.5"
    
     step([$class: 'NexusArtifactUploader',
     artifactId: 'piazza-ingest', classifier: 'artifact',
     credentialsId: 'b9bc9cc5-871e-4738-88f3-9c3e5525a096',
     file: '/var/lib/jenkins/workspace/jenkinsfiletest1/spring-boot-samples/spring-boot-sample-atmosphere/target/piazza-ingest-1.0.0.jar',
     groupId: 'org.venice.piazza',
     nexusUrl: '35.163.156.3:8081/nexus', 
     nexusVersion: 'NEXUS2', protocol: 'http',
     repository: 'releases', type: 'jar', version: '1.5']) 
     
     
       
     }


  }

 }
}
